name: Playwright Portfolio Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests and generate Allure report
        env:
          TEST_ENV: dev  # Your environment name
          CI: true       # Prevent browser-based operations
        run: |
          npm run clear-allure-reports
          npm run run-test
          npm run generate-allure-report

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results/
          retention-days: 90

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report/
          retention-days: 90

      - name: Install ngrok
        run: npm install -g ngrok

      - name: Serve Allure Report using ngrok
        run: |
         npx http-server allure-report -p 5050 &
         ngrok http 5050 > ngrok-url.log &
         sleep 10
         cat ngrok-url.log

      - name: Print Public Allure Report URL
        run: |
         echo "📌 **Access the Allure Report Here:** $(cat ngrok-url.log | grep -o 'https://[a-zA-Z0-9.-]*.ngrok.io')"