name: Playwright Portfolio Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests and generate Allure report
        env:
          TEST_ENV: dev  # Your environment name
          CI: true       # Prevent browser-based operations
        run: |
          npm run clear-allure-reports
          npm run run-test
          npm run generate-allure-report

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results/
          retention-days: 90

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report/
          retention-days: 90

      - name: Serve Allure Report Locally
        if: always()
        run: |
          npm install -g http-server
          npx http-server allure-report -p 5050 &

      - name: Print Local Allure Report URL
        if: always()
        run: |
          echo "📌 **View the Allure Report Locally**: http://127.0.0.1:5050/index.html"
